### ISSUE TITLE
Some BMWs are EV only

### ISSUE THREAD

**Issue by DENightOne** [hdurdle/MMM-BMWConnected#1]
Thanks for the awesome module for MagicMirror..... I changed it a little as my i3 is EV only and I didnt like seeing NaN next to the Petrol Icon :)

![BMW](https://user-images.githubusercontent.com/24840753/66550917-aa5d7380-eb46-11e9-80ad-cd5daaa22a85.png)

**Comment by EPIC-Snake** [comment]
Hi,

you'll need to comment out two lines in _this file:_

cd MagicMirror
cd modules
cd MMM-BMWConnected
sudo nano MMM-BMWConnected.js

**in the script, almost at the end of the script; under var fuelRange comment out like this:**

var fuelRange = document.createElement("span");
    fuelRange.classList.add("fuelRange");
 //   fuelRange.appendChild(this.faIconFactory("fa-gas-pump"));
 //   fuelRange.appendChild(document.createTextNode(info.fuelRange + " " + distanceSuffix));
    carContainer.appendChild(fuelRange);
    wrapper.appendChild(carContainer);

**Comment by jannekalliola** [comment]
I've added support to this feature in pull request #7
