### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by traktorjoe** [hdurdle/MMM-BMWConnected#10]
Hi all,

I am getting the following error, any idea how to resolve that?
`Failed to read list of vehicles:Error: getaddrinfo ENOTFOUND http://www.bmw-connecteddrive.com`

Thanks

**Comment by jannekalliola** [comment]
BMW changed their authentication mechanism. Please try out https://github.com/jannekalliola/MMM-BMWConnected

It contains authentication changes made by @yfre and then my changes to deal with electric cars.
