### ISSUE TITLE
failed to read file

### ISSUE THREAD

**Issue by shgtjgh** [hdurdle/MMM-BMWConnected#12]
Hi all,
any suggestions to solve this?
got this message : 
failed to read file: Error: ENOENT: no such file or directory, open 'modules/MMM-BMWConnected/bmwtoken.json'
failed to read token: coudn't find token in response
thx

**Comment by jannekalliola** [comment]
Please try out https://github.com/jannekalliola/MMM-BMWConnected 

It contains authentication changes made by @yfre and then my changes to deal with electric cars.
