### ISSUE TITLE
Defunct project – way forward

### ISSUE THREAD

**Issue by jannekalliola** [hdurdle/MMM-BMWConnected#14]
The project development seems to be stalled for several years and the project itself is in defunct state due to BMW authentication changes. New development happens in forks and it is not a good and future-proof way to move forward with the system.

As there are people using this module, something should happen. I see three scenarios:

1. @hdurdle activates again and merges the most recent fork back to the trunk.
2. @hdurdle gives the repo to someone else to maintain or grants maintaining rights while keeping the repo in its current location
3. Someone takes over by copying the contents of the repo into a new repo and work continues there

I would like to hear from @hdurdle about the future. If there is no response in a couple of weeks, I think that it is time to move on with option 3. I am willing to make the copy, but if there are people willing to maintain the code, I don't mind not being the owner of the new repo.

I urge everyone following the project to discuss the issue. I'm notifying people who have commented in the recent tickets: @shgtjgh, @SAR71, @chris-wei-17, @nuttersrest, @Spieke96, @stutoni, @yfre, @traktorjoe, @musicnrw, @maximilianfriedrich, @ChrizZz90, @philmavedzenge, @rayzx1994, @Mathein2020, @chansters, @jackmeyer, @keith760, @gbassaragh

The most current codebase is here: https://github.com/jannekalliola/MMM-BMWConnected

**Comment by hdurdle** [comment]
I no longer use Magic Mirror, so this repo will be archived.  Suggest people use Janne's codebase going forward - I will link to it from the readme.
