### ISSUE TITLE
Mini vehicle

### ISSUE THREAD

**Issue by djvanas** [hdurdle/MMM-BMWConnected#3]
Hi!

I have installed the module and would liek to use it with my Mini Clubman vehicle. The module installed, but it only shows "LOADING" and it does not show any data.

Am I doung something wrong or is it just not comaptible with Mini vehicle's?

Tnx, David

**Comment by cherifya** [comment]
Same issue. It's only showing "Loading" for me as well.

**Comment by mrangryoven** [comment]
Same here, i have been to Hdurdle's profile and run the BMW Powershell scripts and it can see my vehicle and pull the data so i am unsure on why this is not working. It even downloaded all the images for my car!
