### ISSUE TITLE
USA apiBase and "Loading..."

### ISSUE THREAD

**Issue by jackmeyer** [hdurdle/MMM-BMWConnected#4]
Hello,

I'm running this module in USA with a USA registered BMW ConnectedDrive vehicle. I added my username/pw in the config as well as apiBase: "https://connecteddrive.bmwusa.com"

is this the right URL for USA? The only error message I can find is in the magicmirror logs, where it says 
Failed to read file: Error: EN0ENT: no such file or directory, open 'modules/MMM-BMWConnected/bmwtoken.json;

seems the token isn't generating. any help to suggest?

Thanks

**Comment by philmavedzenge** [comment]
Mine worked after I changed the locale to my country in the token manager.js which is in the lib folder.

**Comment by keith760** [comment]
I also am having this same exact issue. I've tried changing the URL in apiBase and I've also tried changing to the locale to "us-en" - neither have worked. Anyone else run into this?

**Comment by philmavedzenge** [comment]
Have you tried "en-US"?

> I also am having this same exact issue. I've tried changing the URL in apiBase and I've also tried changing to the locale to "us-en" - neither have worked. Anyone else run into this?

**Comment by keith760** [comment]
> Have you tried "en-US"?
> 
> > I also am having this same exact issue. I've tried changing the URL in apiBase and I've also tried changing to the locale to "us-en" - neither have worked. Anyone else run into this?

Yes - I tried that too. Could it be I have the apiBase URL incorrect? Anything else I could try?

**Comment by philmavedzenge** [comment]
I Downloaded the powershell folder and tested my credentials and API endpoint. Check if you get any information back

**Comment by philmavedzenge** [comment]
> > Have you tried "en-US"?
> > > I also am having this same exact issue. I've tried changing the URL in apiBase and I've also tried changing to the locale to "us-en" - neither have worked. Anyone else run into this?
> 
> Yes - I tried that too. Could it be I have the apiBase URL incorrect? Anything else I could try?

Hi i have made a few changes that might work for USA accounts. Let me know if you would want to setup my version which is based on the original one.

**Comment by keith760** [comment]
> > > Have you tried "en-US"?
> > > > I also am having this same exact issue. I've tried changing the URL in apiBase and I've also tried changing to the locale to "us-en" - neither have worked. Anyone else run into this?
> > 
> > 
> > Yes - I tried that too. Could it be I have the apiBase URL incorrect? Anything else I could try?
> 
> Hi i have made a few changes that might work for USA accounts. Let me know if you would want to setup my version which is based on the original one.

Hi! I'd love to try your setup out. Is it working for you? I tried downloading your forked version and it did not work

**Comment by philmavedzenge** [comment]
> > > > Have you tried "en-US"?
> > > > > I also am having this same exact issue. I've tried changing the URL in apiBase and I've also tried changing to the locale to "us-en" - neither have worked. Anyone else run into this?
> > > 
> > > 
> > > Yes - I tried that too. Could it be I have the apiBase URL incorrect? Anything else I could try?
> > 
> > 
> > Hi i have made a few changes that might work for USA accounts. Let me know if you would want to setup my version which is based on the original one.
> 
> Hi! I'd love to try your setup out. Is it working for you? I tried downloading your forked version and it did not work

Hi I hadn't committed the code. Try again and give me feedback on the forked version page. Thanks

**Comment by gbassaragh** [comment]
I'm having the same issue, USA locale and have tried the same things, were you able to resolve?
