### ISSUE TITLE
Failed to parse data

### ISSUE THREAD

**Issue by rayzx1994** [hdurdle/MMM-BMWConnected#5]
At first I got a error to read token: Couldn't find token in response. But that randomly went away. Now I am getting 2 errors. Failed to parse data, error SyntaxError: Unexpected end of JSON input. Failed to parse data Wrong vin!, error SyntaxError: Unexpected token W in JSON at position 0. Any ideas?

**Comment by Mathein2020** [comment]
I have the same problem. Any Ideas?

**Comment by philmavedzenge** [comment]
> I have the same problem. Any Ideas?
Hi, try my version which is based on this one. It has been working for me and may work for you.

**Comment by philmavedzenge** [comment]
> I have the same problem. Any Ideas?

Hi try my version which is based on this one. It works for my region and it may work for you.

**Comment by chansters** [comment]
> > I have the same problem. Any Ideas?
> 
> Hi try my version which is based on this one. It works for my region and it may work for you.

I'm having trouble getting this to work as well.  How can I try your version @philmavedzenge ?  I'm in the US.

**Comment by philmavedzenge** [comment]
> > > I have the same problem. Any Ideas?
> > 
> > Hi try my version which is based on this one. It works for my region and it may work for you.
> 
> I'm having trouble getting this to work as well.  How can I try your version @philmavedzenge ?  I'm in the US. 

Hi, so I made changes to the original one and it has always worked for me. Go on my profile and select the BMW module. The instructions will be there.

Let me know if it works for you or the errors you get.

**Comment by chansters** [comment]
> > > > I have the same problem. Any Ideas?
> > > 
> > > 
> > > Hi try my version which is based on this one. It works for my region and it may work for you.
> > 
> > 
> > I'm having trouble getting this to work as well.  How can I try your version @philmavedzenge ?  I'm in the US.
> 
> Hi, so I made changes to the original one and it has always worked for me. Go on my profile and select the BMW module. The instructions will be there.
> 
> Let me know if it works for you or the errors you get.

Thanks Phil for sharing your fork! Unfortunately it still doesn't work for me. :(. This is the only relevant line that I can see in the log : 

`Failed to read file: Error: ENOENT: no such file or directory, open 'modules/MMM-BMWConnected/bmwtoken.json'`

My config is : 

`        {
            module: "MMM-BMWConnected",
            header: 'BMW i3',
            position: "bottom_right",
            config: {
                email: "my email",
                password: "my password",
                distance: "miles",
                refresh: 60,
                vehicleAngle: 10,
                country: "USA", //Type exactly as it appears on https://www.bmw-connecteddrive.com/
                region: "NORTH_AMERICA" //Choose one : NORTH_AMERICA,CHINA,REST_OF_WORLD
            }
        },`
