### ISSUE TITLE
No data loaded

### ISSUE THREAD

**Issue by musicnrw** [hdurdle/MMM-BMWConnected#6]
Since yesterday the modules display "Lade..."(loading...) and no information is displayed anymore

**Comment by maximilianfriedrich** [comment]
same here

**Comment by ChrizZz90** [comment]
same - did you find a way to solve it?

**Comment by musicnrw** [comment]
No, still not working -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 07.04.21, 21:55 schrieb ChrizZz90 ***@***.***>:

   
  same - did you find a way to solve it?

**Comment by philmavedzenge** [comment]
please try my [fork,](https://github.com/philmavedzenge/MMM-BMWConnected) and change the config according to your region. Here in South Africa it's working now that i added apiBase to the config. Also note i don't have an electric vehicle so i removed all electric vehicle specific parameters from the module.

**Comment by musicnrw** [comment]
Hi Philip,thanks for your message. I've installed your fork and in combination with apiBase set to co.za it works. Using .de results in "loading data"... I dont know why, but it's fine for me to get it back to work with our help.Have a nice day!! Best regards,Thomas-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.04.21, 12:30 schrieb Philip Mavedzenge ***@***.***>:

   
  please try my fork, and change the config according to your region. Here in South Africa it's working now that i added apiBase to the config. Also note i don't have an electric vehicle so i removed all electric vehicle specific parameters from the module.

**Comment by philmavedzenge** [comment]
> Hi Philip,thanks for your message. I've installed your fork and in combination with apiBase set to co.za it works. Using .de results in "loading data"... I dont know why, but it's fine for me to get it back to work with our help.Have a nice day!! Best regards,Thomas-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.04.21, 12:30 schrieb Philip Mavedzenge ***@***.***>: please try my fork, and change the config according to your region. Here in South Africa it's working now that i added apiBase to the config. Also note i don't have an electric vehicle so i removed all electric vehicle specific parameters from the module. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Hi, 

I'm really pleased that it worked for you as well.

Philip

**Comment by musicnrw** [comment]
Hi Philip,as I also have a non-electric BMW, can you please send me the modified file where you removed the electric vehicle specific parameters?Thanks a lot for your help!!Thomas-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.04.21, 13:41 schrieb Philip Mavedzenge ***@***.***>:

   
   
   Hi Philip,thanks for your message. I've installed your fork and in combination with apiBase set to co.za it works. Using .de results in "loading data"... I dont know why, but it's fine for me to get it back to work with our help.Have a nice day!! Best regards,Thomas-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.04.21, 12:30 schrieb Philip Mavedzenge @.***>: please try my fork, and change the config according to your region. Here in South Africa it's working now that i added apiBase to the config. Also note i don't have an electric vehicle so i removed all electric vehicle specific parameters from the module. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
   
  Hi, 
  I'm really pleased that it worked for you as well. 
  Philip

**Comment by philmavedzenge** [comment]
Hi check [this](https://github.com/philmavedzenge/MMM-BMWConnected/blob/master/MMM-BMWConnected.js) file. I may have changed more things but you will have to compare the original file to mine.

**Comment by ChrizZz90** [comment]
@musicnrw I guess you can also use www.bmw-connecteddrive.com, I believe there isn't a *.de version of the API.

**Comment by musicnrw** [comment]
Thank, yes. I know have it working again by help of a community member from South Africa. I am wondering why it worked fine over months and then suddenly stopped. -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.04.21, 19:37 schrieb ChrizZz90 ***@***.***>:

   
  @musicnrw I guess you can also use www.bmw-connecteddrive.com, I believe there isn't a *.de version of the API.

**Comment by ChrizZz90** [comment]
what did you do to make it work again? Still with @philmavedzenge 's repository I get the same "loading" message. My config section:

`{
			module: "MMM-BMWConnected",
   			header: 'BMW Connected',
   			position: "bottom_right",
			classes: "chris",
       			config: {
           			email: "XXX",
           			password: "XXX",
					apiBase: "www.bmw-connecteddrive.co.za",
					distance: "km",
					refresh: "15",
					vehicleAngle: "10",
					country: "Germany",
					region: "REST_OF_WORLD"
   					}
		},`

**Comment by maximilianfriedrich** [comment]
For me changing the apiBase to www.bmw-connecteddrive.com did the magic. 

Thanks!

**Comment by musicnrw** [comment]
My Definition in the config.js für BMWConnected looks like this and it works:



{

    module: "MMM-BMWConnected",

    header: 'BMW Connected',

    position: "top_right",

    config: {

        email: "xxxxx",

        password: "yyyyy",

    apiBase: "www.bmw-connecteddrive.co.za", //this works for me in South Africa not sure what other regions would be

        distance: "km",

        refresh: 15,

        vehicleAngle: 80,

    country: "South Africa", //Type exactly as it appears on https://www.bmw-connecteddrive.com/

    region: "REST_OF_WORLD" //Choose one : NORTH_AMERICA,CHINA,REST_OF_WORLD

    }

},

Von: ChrizZz90 ***@***.***> 
Gesendet: Donnerstag, 8. April 2021 21:13
An: hdurdle/MMM-BMWConnected ***@***.***>
Cc: musicnrw ***@***.***>; Mention ***@***.***>
Betreff: Re: [hdurdle/MMM-BMWConnected] No data loaded (#6)

 

what did you do to make it work again? Still with @philmavedzenge <https://github.com/philmavedzenge>  's repository I get the same "loading" message. My config section:

{ module: "MMM-BMWConnected", header: 'BMW Connected', position: "bottom_right", classes: "chris", config: { email: "XXX", password: "XXX", apiBase: "www.bmw-connecteddrive.co.za <http://www.bmw-connecteddrive.co.za> ", distance: "km", refresh: "15", vehicleAngle: "10", country: "Germany", region: "REST_OF_WORLD" } },

**Comment by jannekalliola** [comment]
Please try out https://github.com/jannekalliola/MMM-BMWConnected

It contains authentication changes made by @yfre and then my changes to deal with electric cars.
