### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by shgtjgh** [hdurdle/MMM-BMWConnected#8]
since Yesterday MagicMirror is just loading, but not showing.
anyone els. ca.6months ago same issue
did it perfect afterwards.
help

**Comment by SAR71** [comment]
Hi @shgtjgh,

I've had the same issue and fixed it by adding 

rejectUnauthorized: false

to bmwrequest.js in the var Options 🙂👍🏼

**Comment by shgtjgh** [comment]
Hi SAR71,
sorry for reacting so late, but on holiday!
Can you elaborate a bit more: I cannot find a bmwrequest.js; the optionfolder in var is empty; where do i put what.
I'am an experienced digibeet ;-)
